token: ''

DSN: ''

manhole_enable: false
manhole_bind: 127.0.0.1:7171

state:
  sync_guild_members: true

control_channels:
  # ID of channels where the control messages should send to
  PRODUCTION: 392854801354063873
  DEVELOPMENT: 392854801354063873

bot:
  commands_enabled: true
  plugins:
    - rowboat.plugins.core
    - rowboat.plugins.modlog
    - rowboat.plugins.admin
    - rowboat.plugins.infractions
    - rowboat.plugins.spam
    - rowboat.plugins.censor
    - rowboat.plugins.reddit
    - rowboat.plugins.starboard
    - rowboat.plugins.utilities
    - rowboat.plugins.sql
    - rowboat.plugins.internal
    - rowboat.plugins.stats
    - rowboat.plugins.tags

web:
  SECRET_KEY: ''
  DOMAIN: bot.i0.tf:8080
  discord:
    CLIENT_ID: 
    CLIENT_SECRET: ''
    API_BASE_URL: 'https://discordapp.com/api'
    TOKEN_URL: 'https://discordapp.com/api/oauth2/token'
    AUTH_URL: 'https://discordapp.com/oauth2/authorize'
    REDIRECT_URI: 'http://bot.i0.tf:8080/api/auth/discord/callback'